### ISSUE TITLE
design coherence

### ISSUE THREAD

**Issue by JeanBarriere** [storyscript/dashboard#142]
### Objective
As a user,
I expect to identify the dashboard as a single design,
But I can already see 3 different styling in the dashboard MVP.
I should see having a similar design,
So that I'm not confused when I change pages.

### Acceptance
**Given** me looking into my app,
**When** I change from the activity list to the service page,
**Then** I see almost the same outlined design

**OR**

**Given** me looking into my app list,
**When** I access to an app and see its activity,
**Then** I see almost the same outlined design

### Notes

This needs to be discussed, created post-feedback
> cc @aydaoz @stevepeak @matthewhudson @Arinono @rohit121

**Comment by aydaoz** [comment]
You are talking about coherence but you mention _same outlined design_ a bit confused. Can you give more example maybe support screenshots or we can get on a call? @JeanBarriere
