### ISSUE TITLE
Storyscript Dashboard Thoughts

### ISSUE THREAD

**Issue by williammartin** [storyscript/dashboard#149]
I will pull this out into other issues:

Apps Dashboard:
 - Dates don't have any context under app name or owner
 - No other owner is supported
 - Environment is always PRODUCTION
 - Not deployed is Unknown
 - Stop vs Maintenance

Services Dashboard:
 - Services are always running 

App Settings:
 - Why are the name and url in forms?
 - Delete app confirm should be clearer about the danger of delete in the button and default to cancel

**Comment by JeanBarriere** [comment]
These have been adressed in the #164
