### ISSUE TITLE
add syntax highlighting component

### ISSUE THREAD

**Issue by JeanBarriere** [storyscript/dashboard#171]
### Objective
As a user,
When I look at some code in the dashboard,
I see different colors and a copy button
So that I can clearly see what language it is and do the related action fast.

### Acceptance
**Given** I'm looking at the no-release page,
**When** I click on the copy button on the code
**Then** I see that the code has been copied to my clipboard.

**AND**

**Given** I'm looking at the no-release page,
**When** I see some code written to help me,
**Then** I see this code is colorful.

**Notes**
Syntax Highlighting should include the storyscript highlighting.
@wilzbach can you please point here to the storyscript repository that includes the highlighting for the language ?

**Comment by wilzbach** [comment]
https://github.com/storyscript/syntax
