### ISSUE TITLE
add proper design on the no-services view

### ISSUE THREAD

**Issue by JeanBarriere** [storyscript/dashboard#185]
### Story
As a Storyscript user,
When I access to the services tab of an application,
And this application has no services being used,
I see that no services are being used, with a link to the [create a story blogpost](https://storyscript.io/blog/story-telling/)

### Acceptance
**Given** I'm logged in to the dashboard,
**When** I navigate to one of my applications which does not use services,
**And** I go the services tab,
**Then** I see the following content displayed in the tab

![image](https://user-images.githubusercontent.com/11390722/66579229-c7ad3480-eb7c-11e9-9580-e474bd1c1271.png)

### Notes

@stevepeak @aydaoz we need validation on the link to follow. It can also be a documentation link

**Comment by Arinono** [comment]
Consensus on the blocker: We remove the button until we have a proper link for it
