### ISSUE TITLE
Storing environment

### ISSUE THREAD

**Issue by stevepeak** [storyscript/dashboard#3]
Environment variables need to be stored in uppercase format so the REST API can return them properly to the engine.

https://github.com/asyncy/platform-engine/issues/23#issuecomment-374581505

**Comment by JeanBarriere** [comment]
Need to uppercase config variables in the settings page.
- uppercase in the input
- re-enforce uppercase when we reassign the variables
- do **not** uppercase the scope

**Comment by stevepeak** [comment]
@JeanBarriere I left a lot of UX feedback with @rohit121 concerning the layout of configuration. There will be no reassigning, because that will never happen. And no "scope", per say, a service has configuration a story has secrets. They cannot change scope and the user needs to have the variables organized accordingly.  For example:

1. I suggest moving service config under the service itself.
2. Story secrets are very different than service configuration, they should not be managed in the same place.
3. Please distinguish between "service Configuration" and "Storyscript Secrets".

**Comment by Arinono** [comment]
@stevepeak @rohit121 I understand your point Steve, but the issue here is to make sure that we validate the keys in caps lock, which is not the case yet. Do we still need to make sure that theses keys are validated for this, if so : we should reopen this one.

**Comment by JeanBarriere** [comment]
Environment being wrongly defined, we are hiding this management feature for now.

Closing, we can open a new issue in the future
