### ISSUE TITLE
create Contribution guidelines

### ISSUE THREAD

**Issue by Arinono** [storyscript/dashboard#48]
In order to avoid pushing to `master` and have unfinished business going to production. We need the add the pre-prod process. This will help see what are the new features and test them before doing the "last" release.

What we need to do is:

- [x] create a `dev` branch from the `master`. This will become the main branch of the project.
- [ ] create the release process in CircleCI
  - [ ] should run `yarn run release` in order to update the `CHANGLEOG.md` + the `package.json`
  - [ ] should run `yarn run pwa-audit` in order to generate the Lighthouse badges on the `README.md`
  - [ ] should create the GH PR 

The only ways to add code to `master` are:
  - Merges from `dev` branch
  - Merges from `hotfix/***` branches. These branches are created from the `master` branch directly

The only ways to add code to `dev` are:
  - Merges from `(!hotfix)/***` branches (feat, fix, refactor, ...).

**Comment by JeanBarriere** [comment]
renaming to **create Contribution guidelines**.
