### ISSUE TITLE
initialize project with vue-cli

### ISSUE THREAD

**Issue by JeanBarriere** [storyscript/dashboard#6]
**The dashboard main role as a MVP is to provide a cohesive UI to create or manage apps and teams. As we want to iterate fast, we need a stable and approved architecture**

- **type of project:** `vue-cli` generated
- **PWA:** enabled but unused for now, we will have notifications and use cases that will need a customer id, or even for a better offline management
- **tests:** enable `jest` so we can test components, and `circleci` so we can automate these
- **style:** we will use `tailwindcss` to generate the style of the dashboard, as it appears to differ a bit from the `@storyscript/vue` library and will help us provide a new gen library set as well.
- **deployment:** `netlify` is still appropriate as it is used by all of our platforms, with previews enabled
- **data management:** install `graphql`, `appolo`, `vuex` for our store management
- **router:** use `vue-router`, may need a pre-handler if we want to have `slug.dash.story.io` for the apps, maybe not
- **data loading:** we need a loading vue or global state to ensure user data is pre-fetched/retrieved before we access any page. It will help for the future PWA as well
- **diagrams:** we need a chart library for diagrams displays, **_see later issue_**

**Comment by Arinono** [comment]
- [x] **type of project:** `vue-cli` generated

- [x] **PWA:** enabled but unused for now, we will have notifications and use cases that will need a customer id, or even for a better offline management

- [x] **tests:** enable `jest` so we can test components

- [ ] **tests:** 100% coverage

- [ ] `circleci` so we can automate these

- [x] **style:** we will use `tailwindcss` to generate the style of the dashboard, as it appears to differ a bit from the `@storyscript/vue` library and will help us provide a new gen library set as well.

- [ ] **deployment:** `netlify` is still appropriate as it is used by all of our platforms, with previews enabled

- [ ] **data management:** install `graphql`, `appolo`, `vuex` for our store management

- [ ] **router:** use `vue-router`, may need a pre-handler if we want to have `slug.dash.story.io` for the apps, maybe not

- [ ] **data loading:** we need a loading vue or global state to ensure user data is pre-fetched/retrieved before we access any page. It will help for the future PWA as well

- [ ] **diagrams:** we need a chart library for diagrams displays, **_see later issue_**
